-- 코드를 입력하세요
SELECT I.REST_ID AS REST_ID, REST_NAME, FOOD_TYPE, FAVORITES, ADDRESS, ROUND(AVG(REVIEW_SCORE), 2) AS SCORE 
FROM REST_INFO AS I JOIN REST_REVIEW AS R
WHERE I.REST_ID = R.REST_ID AND I.ADDRESS LIKE '서울%'
GROUP BY REST_NAME
ORDER BY SCORE DESC, FAVORITES DESC;